name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - movix-dev  # Change this to your deployment branch

permissions:
  contents: write  # Grant write permissions for repository contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Token for authentication
        publish_dir: ./dist  # Directory to publish
